### PR TITLE
Fix stratum bf retrieve value

### LINKED ISSUE #316: Failed to build `stratum-bf`
**Describe the bug**
`stratum-bf` build fails with error in `bf_switch.cc`

**Environment**
Jenkins

Switch:
N/A

**To Reproduce**
1. Run build-stratum-bf-container.sh script from stratum/hal/bin/barefoot/docker
2. Build fails with this error:
```stratum/hal/lib/barefoot/bf_switch.cc: In member function 'virtual util::Status stratum::hal::barefoot::BFSwitch::RetrieveValue(stratum::uint64, const stratum::hal::DataRequest&, stratum::hal::WriterInterface<stratum::hal::DataResponse>*, std::vector<util::Status>*)':

stratum/hal/lib/barefoot/bf_switch.cc:233:32: error: 'class util::StatusOr<stratum::hal::DataResponse>' has no member named 'mutable_node_info'

         auto* node_info = resp.mutable_node_info();

                                ^~~~~~~~~~~~~~~~~
```

### PR DESCRIPTION
**Pull request by pudelkoM**
Fixes #316

### CODE REVIEW

File: stratum/hal/lib/barefoot/bf_chassis_manager.h [hunk 1]
```diff
@@ -111,9 +114,6 @@ class BFChassisManager {
   ::util::Status RegisterEventWriters() EXCLUSIVE_LOCKS_REQUIRED(chassis_lock);
   ::util::Status UnregisterEventWriters() LOCKS_EXCLUDED(chassis_lock);
 
-  ::util::StatusOr<int> GetUnitFromNodeId(uint64 node_id) const
-      SHARED_LOCKS_REQUIRED(chassis_lock);
-
```
Comment (pudelkoM) [inline stratum/hal/lib/barefoot/bf_chassis_manager.h:116]: This move is in preparation for implementing chip information on stratum bfrt.
