### PR TITLE
Prevent DirectCounterEntry modifies from changing the action data

### LINKED ISSUE #685: Action parameter(s) will be reset if set the direct counter
**Describe the bug**

When sending write request to set the direct counter, the action parameter of that table entry will also be reset to default value(e.g., zero)

**Environment**

 - Stratum bfrt container image
   - SDE 9.5.0 
   - Commit: `155588e6031853f0c0122fec823dba91571ac3a8`
 - Tofino Model

**To Reproduce**

Use P4Runtime Shell with fabric-tna:

```python3
te = table_entry['FabricIngress.stats.flows'](action='FabricIngress.stats.count')
te.priority = 10
te.match['ig_port'] = '1'
te.action['flow_id'] = '1'
te.insert()
te.read(lambda x: print(x)) # value of parameter is 1

dce = direct_counter_entry['FabricIngress.stats.flow_counter']
dce.table_entry.match['ig_port'] = '1'
dce.table_entry.priority = 10
dce.byte_count = 0
dce.packet_count = 0
dce.modify()

te.read(lambda x: print(x)) # value of parameter becomes 0
```

**Expected behavior**

The value of parameter should still be `1`

### PR DESCRIPTION
**Pull request by pudelkoM**
This change removes `SetOnlyCounterData` which erroneously *did* modify the action data and replaces it with the existing `SetCounterData` function. We improve the later by only setting BfRt table data fields that exists, e.g., in byte-only counters.

Fixes #685

### CODE REVIEW

**Comment by pudelkoM** [comment]
@Yi-Tseng could you give this PR a try? I'm fairly certain I got it, but a second look would not hurt.

File: stratum/hal/lib/barefoot/bfrt_table_manager.cc [hunk 1]
```diff
@@ -685,8 +685,9 @@ ::util::Status BfrtTableManager::WriteDirectCounterEntry(
   RETURN_IF_ERROR(BuildTableKey(table_entry, table_key.get()));
 
   // Fetch existing entry with action data. This is needed since the P4RT
-  // request does not provide the action (id), but the SDE requires it in the
-  // later modify call.
+  // request does not provide the action (id) and action data, but we have to
```
Comment (pudelkoM) [inline stratum/hal/lib/barefoot/bfrt_table_manager.cc:688]:
```suggestion
  // request does not provide the action ID and data, but we have to
```

**Review by Yi-Tseng — APPROVED** [review]
LGTM, and the PTF test pass with this fix

**Comment by pudelkoM** [comment]
> LGTM, and the PTF test pass with this fix

Thanks for checking!
