### PR TITLE
fixes stratum/stratum#230

### LINKED ISSUE #230: np4_intel platform build is broken
**Describe the bug**
The np4_intel platform build fails on stratum/hal/bin/np4intel/main.cc Main function as per the messages below in this issue.

**Environment**
Using the `setup_dev_env.sh --np4-intel` containerised bazel build environment to build the np4_intel binary using the following command:
bazel build //stratum/hal/bin/np4_intel:stratum_np4intel

If building from source:
`bazel version`
Starting local Bazel server and connecting to it...
Build label: 2.2.0
Build target: bazel-out/k8-opt/bin/src/main/java/com/google/devtools/build/lib/bazel/BazelServer_deploy.jar
Build time: Tue Mar 3 09:26:12 2020 (1583227572)
Build timestamp: 1583227572
Build timestamp as int: 1583227572

Switch:
Intel PAC N3000

**To Reproduce**
1. setup_dev_env.sh --np4-intel
2. bazel build //stratum/hal/bin/np4_intel:stratum_np4intel
3. See these errors
stratum/hal/bin/np4intel/main.cc: In function 'int stratum::hal::np4intel::Main(int, char**)':
stratum/hal/bin/np4intel/main.cc:142:56: error: 'class util::StatusOr<std::unique_ptr<stratum::CredentialsManager> >' has no member named 'get'
                                    credentials_manager.get());
                                                        ^~~
Target //stratum/hal/bin/np4intel:stratum_np4intel failed to build

**Expected behavior**
The build should complete successfully.

**Additional context**
I believe this was introduced in the original PR for the np4_intel platform during one of the merges from master.

### PR DESCRIPTION
**Pull request by craigsdell**
- fix broken build for np4_intel platform (main.cc)
- changed containter build script to use Netcope Ubuntu SDK binary
- test to make sure Netcope SDK binary checksum matches the build script
- added option to build script to skip checksum testing (can be used to
  build different versions of the Netcope Ubuntu SDK binary for testing).
- updated README to reflect build script changes

Fixes #230

### CODE REVIEW

File: stratum/hal/bin/np4intel/docker/build-stratum-np4intel-container.sh [hunk 1]
```diff
@@ -56,16 +62,29 @@ fi
...
+    NP4_BIN=$(basename $1)
+    BUILD_ARGS="$BUILD_ARGS --build-arg NP4_BIN=$NP4_BIN"
     cp -f $1 $DOCKERFILE_DIR
 fi
 
+# Make sure the Netcope SDK binary matches our checksum
+if [ "$SKIP_MD5" != YES ]; then
+    NP4_MD5=${NP4_BIN:0:-4}.md5
+    echo "$NP4_CHKSUM $NP4_BIN" >$NP4_MD5
+    md5sum -c $NP4_MD5
```
Comment (pudelkoM) [inline stratum/hal/bin/np4intel/docker/build-stratum-np4intel-container.sh:79]: just no

Comment (craigsdell) [reply stratum/hal/bin/np4intel/docker/build-stratum-np4intel-container.sh:79]: Well I guess that reads better, but will also require that we set NP4_MD5 to NO as the default if the switch is not set.
